### ISSUE TITLE
Creating load balancer failed Reason...

### ISSUE THREAD

**Issue by tomfa** [helleroy/beanstalk-workshop#5]
`Creating load balancer failed Reason: Default subnet in eu-west-1b not found`

Har visst lekt meg litt masse, så klart å slette et default subnet tidligere. Antar jeg ikke er den eneste av gruppa som har klart det. Fint om det er litt hjelp om man får en sånn feil

**Comment by helleroy** [comment]
Den raskeste måten å fikse det på er kanskje å terminere appen og sette den opp på nytt?
Her hadde Terraform kunnet hjelpe til ved at man da kan røske ned hele skiten og sette den opp på nytt uten noe ekstra arbeid - "Immutable infrastructure" style. Jeg kan ta en titt på det ila. helgen hvis det virker kult?
